services:
  postgres:
    image: postgres:16-alpine
    container_name: gestauto_postgres
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    
    depends_on:
      - postgres