-- AlterTable
ALTER TABLE "Empresa" ALTER COLUMN "cnpj" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "uf" SET DATA TYPE VARCHAR(10);

-- AlterTable
ALTER TABLE "UsuarioEmpresa" ALTER COLUMN "funcao" DROP NOT NULL,
ALTER COLUMN "permisso" DROP NOT NULL;
